### ISSUE TITLE
To-do for Theme

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#87]
### **Light theme**
To-do:

- [x] Correct the background color
- [x] Change the font size
- [x] Change the font color for inactive "Translate" button

For the information windows below:

![obraz](https://user-images.githubusercontent.com/47037905/134383177-bb50ad09-4805-4674-a585-f23d346c7d18.png)

![obraz](https://user-images.githubusercontent.com/47037905/134387257-b4668cad-a16c-4796-b95f-c22a2353c594.png)

Changing the font color for inactive "Translate" button:

![obraz](https://user-images.githubusercontent.com/47037905/134782375-8db9775d-9e8c-4331-8193-48180f43b053.png)

![obraz](https://user-images.githubusercontent.com/47037905/134781952-30ea976c-ff51-478e-9880-50b4dde7211c.png)

----------------
### **Dark theme**
To-do:

- [x] Add the green application bar (see screenshot)

![obraz](https://user-images.githubusercontent.com/47037905/134549079-53bad9e9-9a89-4bb9-87ab-98269342bca8.png)

**Comment by ManeraKai** [comment]
> Change translator selection bar (see screenshot)

@Valdnet You mean the engine TabBar?

**Comment by Valdnet** [comment]
> You mean the engine TabBar?

Yes, but after resigning from xxx, I only suggest extending the beam to the width of the entire application. This will emphasize its dominant color.

New screenshot:

![obraz](https://user-images.githubusercontent.com/47037905/134549079-53bad9e9-9a89-4bb9-87ab-98269342bca8.png)

Changed to-do list.

**Comment by ManeraKai** [comment]
FontSize wise, here's how it looks on the standard emulator:
<img width=360 src="https://user-images.githubusercontent.com/40805353/134571906-eb81c29e-f54a-40a4-bc20-62a657572706.png">

**Comment by Valdnet** [comment]
Have you changed the font size? Does it look like this on the emulator without changing?
It looks a little bigger on my smartphone.

**Comment by ManeraKai** [comment]
I didn't change the FontSize.

**Comment by Valdnet** [comment]
Hmmm... It seems to me that it is bigger on my smartphone. We will see what it will look like on a white background 😉.

For now, I'll mark the to-do list.

**Comment by Valdnet** [comment]
In the light theme, change the font color for the inactive "Translate" button to a very light gray. Also change the font color for the "Translate" button at the top of the keyboard.

Currently:

![obraz](https://user-images.githubusercontent.com/47037905/134782375-8db9775d-9e8c-4331-8193-48180f43b053.png)

After change:

![obraz](https://user-images.githubusercontent.com/47037905/134782441-972f839e-888b-48b8-ae67-3ef365e7f048.png)

Currently:

![obraz](https://user-images.githubusercontent.com/47037905/134781952-30ea976c-ff51-478e-9880-50b4dde7211c.png)

After change:

![obraz](https://user-images.githubusercontent.com/47037905/134782421-9d1dfc6f-c6b8-4aba-a22a-a524d3293248.png)

**Comment by ManeraKai** [comment]
Are you sure the photos aren't the same?

**Comment by Valdnet** [comment]
> Are you sure the photos aren't the same?

Are not. The white font color for inactive "Translate" buttons should be changed to **very light gray**. So that the font is not white, because it looks as if the text is transparent and does not match gray as well.

**Comment by ManeraKai** [comment]
I'm sorry, my screen didn't detect change. Changed color profile to see the difference. I have some contrast problems with white colors on it.

**Comment by ManeraKai** [comment]
It's not a very light grey. It's a little dark. If you didn't like that, tell me.

**Comment by ManeraKai** [comment]
https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1273670750

**Comment by ManeraKai** [comment]
Did you like the grey color?

**Comment by Valdnet** [comment]
It is so beautiful 😁. Thanks 😉. I close the issue.

If I find anything else about the appearance, I'll open it again.
